const fs = require('fs');
const path = require('path');

const dir = 'src/components';
const files = fs.readdirSync(dir).filter(f => f.endsWith('.tsx'));

files.forEach(file => {
  const filePath = path.join(dir, file);
  let content = fs.readFileSync(filePath, 'utf8');
  let originalContent = content;

  // Fix recursive mess generated by previous replacements
  const messPatterns = [
    /bg-white\/5 backdrop-blur-xl border border-white\/10\/5 backdrop-blur-xl border border-white\/10/g,
    /bg-white\/5 backdrop-blur-xl border border-white\/10\/5 backdrop-blur-xl\/[0-9]{2}/g,
    /bg-white\/5 backdrop-blur-xl border border-white\/10\/[0-9]{1,2}/g,
    /bg-white\/5 backdrop-blur-xl border border-white\/10\/5 backdrop-blur-xl/g,
    /hover:bg-white\/5 backdrop-blur-xl border border-white\/10\/10/g,
    /hover:bg-white\/5 backdrop-blur-xl border border-white\/10\/5/g,
    /border border-white\/10\/70/g,
    /border border-white\/10\/10/g,
    /border border-white\/10\/20/g,
    /border border-white\/10\/5/g,
    /bg-white\/5 backdrop-blur-xl border border-white\/10 border border-white\/10/g,
    /bg-white\/5 backdrop-blur-xl border border-white\/5/g
  ];

  messPatterns.forEach(pattern => {
    content = content.replace(pattern, 'bg-white/5 backdrop-blur-xl border border-white/10');
  });

  // some specific hovers
  content = content.replace(/hover:bg-white\/5 backdrop-blur-xl border border-white\/10/g, 'hover:bg-white/10');
  
  // also clean up any duplicate "border border-white/10"
  content = content.replace(/border border-white\/10 border border-white\/10/g, 'border border-white/10');
  
  // Also fix double backgrounds like `bg-white/5 backdrop-blur-xl bg-white/5 backdrop-blur-xl`
  content = content.replace(/(bg-white\/5 backdrop-blur-xl\s*){2,}/g, 'bg-white/5 backdrop-blur-xl ');
  content = content.replace(/(border border-white\/10\s*){2,}/g, 'border border-white/10 ');

  if (content !== originalContent) {
    fs.writeFileSync(filePath, content);
    console.log('Cleaned', file);
  }
});
